services:
  postgres:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d project"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    container_name: backend
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgresql://user:password@postgres:5432/project
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
